version: '3'
services:
  bedrock:
    build: ./build/bedrock
    image: bedrock
    container_name: website-bedrock
    restart: always
    volumes:            
      - ./config/custom.php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./www:/share/nginx/html
    ports:
      - "9000:9000"
    environment:
      PHP_FPM_USER: www-data
      PHP_FPM_GROUP: www-data

  server:
    image: nginx:latest
    container_name: website-nginx
    restart: always
    volumes:
      - ./config/site.template:/etc/nginx/conf.d/site.template
      - ./www:/share/nginx/html
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=docker-test.local
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
  
  db:
    image: mariadb:10.3
    container_name: website-db
    restart: always
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database

  adminer:
    image: adminer
    container_name: website-adminer
    restart: always 
    ports:
      - 8080:8080